language: node_js

node_js:
  - 8

script:
  - yarn lint
  - yarn test

notifications:
  slack:
    rooms:
      secure: UK1etQS/UAuKH1olUVU9UjMET/JyZoq3FTSwk8VVGXWvD9MQLmeE4smeX7DNDBC++0hBLV/ey6g2xnhlLJkY7mWSvhuq4yyhWLskyh9t1uuP8TwzhHQ1or4YwtQMrgwodYYAfLJcMTNl7y47Yoed4wj6mE+stz8CveGa2ntDF/mpN6opuZupl276/qMDGCywZumxqecqk8gRlMoohTC3CPPkV7P4HnnogFdlYUbWhEbP69izg8Br257mtfZmwHW+YwuvQza5pJsIrRHB84KU8GREvcMTOPtLGQMt8x7BElxOzzO8BkV2yE7X2BauWGvTWeTGheHEpdtp5FxqajGayh2uOdstEO6QO5XLq7s1QfnJn3WrMA96LL0JvNpnKIOYAeGXqqpPhL7Yxb5Vu7T2U/Wpq/PZFjgvYH7VU75/oiOV7ebmjpsFb9aH8yTslKq3E0C5TR0lqOj/0uXyP2o5Egclt451VZSVnCtS8/GXHB7QN23a6CE0JP7kURoUf15oA7Tz5tRFv7TiqtdKuchZB9CKyfYFgqJM+q/FxCGniHNkpT5SuM/Y5SYpbyNv8epUjwYnLuKkXmXprC013CSKoiduXtaq2hLE06SkqUylkxvXbuA8qQ8QsLSK0t2+Q8ug/M76jndpEO09UwLNsUZudTAXy2By9E4HF1hKhg66VBM=
